import assert from 'node:assert/strict';
const saved=new Map();
globalThis.localStorage={getItem:k=>saved.get(k)??null,setItem:(k,v)=>saved.set(k,v)};
globalThis.location={search:'',href:'https://example.test/?lang=en'};
globalThis.history={replaceState:(_a,_b,url)=>{location.href=String(url)}};
globalThis.matchMedia=()=>({matches:false});globalThis.devicePixelRatio=1;
const quality=await import('../src/render-quality.ts');
assert.equal(quality.getRenderQuality(),'high','Desktop starts in Fine');
assert.equal(quality.renderPixelRatio(1280,720),2);
let events=0;quality.onRenderQuality(()=>events++);
quality.setRenderQuality('ultra');
assert.equal(quality.renderPixelRatio(1280,720),3);
assert(quality.renderPixelRatio(3840,2160)*3840<=4096,'Bound GPU longest edge');
assert.equal(saved.get('turbine-quality'),'ultra');
assert.equal(new URL(location.href).searchParams.get('lang'),'en');
assert.equal(new URL(location.href).searchParams.get('quality'),'ultra');
quality.setRenderQuality('balanced');assert.equal(events,2);
assert.equal(quality.renderPixelRatio(1280,720),1);
console.log('PASS: default quality, supersampling, GPU size cap, saved preference and shared change events.');
